language: node_js

sudo: false

node_js:
  - "stable"

before_script:
  - "npm install -g codeclimate-test-reporter"
  - "export TZ=Europe/Warsaw"

after_success:
  - "npm run coverage"
  - "codeclimate-test-reporter < coverage/lcov.info"
